### ISSUE TITLE
Can't drag after using 'handleDragstart'?

### ISSUE THREAD

**Issue by lsl233** [formkit/drag-and-drop#20]
```Javascript
const dragAndDropOptions: Partial<ParentConfig$1<Webpage.Row>> = {
  group: 'tagWebpages',
  // Remove 'handleDragstart' and you can drag
  handleDragstart(data) {
    moving = true
  },
  handleEnd() {
    moving = false
  }
}
```

**Comment by andrew-boyd** [comment]
@lsl233 Hey there! So when you assign an event handler to the config, you are overriding the event entirely. If you would still like to execute the original dragstart handler, then do something like this:

```js
import { handleDragstart } from '@formkit/drag-and-drop'
const dragAndDropOptions: Partial<ParentConfig$1<Webpage.Row>> = {
  group: 'tagWebpages',
  handleDragstart(data) {
    moving = true
    handleDragstart(data)
  },
  handleEnd() {
    moving = false
  }
}
```

FWIW, we plan to implement events that you can listen to (instead of overriding the even handler itself), but this should work for now. I'll go ahead and close this for now but let me know if you have anymore questions and we can reopen this.

**Comment by lsl233** [comment]
Ok, I see, thanks for your answer
