### ISSUE TITLE
Documentation: Defining `handleEnd` (or any event handler) in the configuration overrides the event handler completely.

### ISSUE THREAD

**Issue by wesharper** [formkit/drag-and-drop#46]
I've experienced this with other handlers, but most recently with `handleEnd`. I have a `handleEnd` function that does nothing but `console.log`, yet it breaks expected behavior on touch devices. Likely due to an event getting canceled when the callback is fired.

Repro: https://codesandbox.io/p/sandbox/fk-drag-touch-repro-forked-fy4pz9?file=%2Fpackage.json%3A12%2C38

Video:

https://github.com/formkit/drag-and-drop/assets/13283469/17074301-0a62-49d1-a150-90ab849f60d1

**Comment by sashamilenkovic** [comment]
@wesharper Ah yes, when you define `handleEnd`, you are actually overriding the core event handler itself. The idea is to import the original `handleEnd` and reinvoke it before or after whatever logic you are trying to add on: [sandbox](https://codesandbox.io/p/sandbox/fk-drag-touch-repro-forked-mxkh4j?file=%2Fsrc%2FApp.vue%3A17%2C21&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522cltwzozhv00073b6hp7yuhd0i%2522%252C%2522sizes%2522%253A%255B100%252C0%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522cltwzozhu00033b6hwhvbxzt8%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522cltwzozhu00043b6h518r410l%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522cltwzozhu00063b6hbhvovj5c%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522cltwzozhu00033b6hwhvbxzt8%2522%253A%257B%2522id%2522%253A%2522cltwzozhu00033b6hwhvbxzt8%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clu0852lf00023b6grmytxmvc%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A17%252C%2522startColumn%2522%253A21%252C%2522endLineNumber%2522%253A17%252C%2522endColumn%2522%253A21%257D%255D%252C%2522filepath%2522%253A%2522%252Fsrc%252FApp.vue%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clu0852lf00023b6grmytxmvc%2522%257D%252C%2522cltwzozhu00063b6hbhvovj5c%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cltwzozhu00053b6hv0ae39js%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522cltwzozhu00063b6hbhvovj5c%2522%252C%2522activeTabId%2522%253A%2522cltwzozhu00053b6hv0ae39js%2522%257D%252C%2522cltwzozhu00043b6h518r410l%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522cltwzozhu00043b6h518r410l%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Afalse%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D). We plan in the future to implement events you can listen to instead of needing to override the handler itself.

**Comment by wesharper** [comment]
Ah, makes sense. Thanks for the feedback. Perhaps there could be an `onEnd` or `onHookName` pattern that doesn't override default behavior but acts more as a way to fire off your own logic?

**Comment by patrickdundas** [comment]
> @wesharper Ah yes, when you define `handleEnd`, you are actually overriding the core event handler itself. The idea is to import the original `handleEnd` and reinvoke it before or after whatever logic you are trying to add on: [sandbox](https://codesandbox.io/p/sandbox/fk-drag-touch-repro-forked-mxkh4j?file=%2Fsrc%2FApp.vue%3A17%2C21&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522cltwzozhv00073b6hp7yuhd0i%2522%252C%2522sizes%2522%253A%255B100%252C0%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522cltwzozhu00033b6hwhvbxzt8%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522cltwzozhu00043b6h518r410l%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522cltwzozhu00063b6hbhvovj5c%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522cltwzozhu00033b6hwhvbxzt8%2522%253A%257B%2522id%2522%253A%2522cltwzozhu00033b6hwhvbxzt8%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clu0852lf00023b6grmytxmvc%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A17%252C%2522startColumn%2522%253A21%252C%2522endLineNumber%2522%253A17%252C%2522endColumn%2522%253A21%257D%255D%252C%2522filepath%2522%253A%2522%252Fsrc%252FApp.vue%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clu0852lf00023b6grmytxmvc%2522%257D%252C%2522cltwzozhu00063b6hbhvovj5c%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cltwzozhu00053b6hv0ae39js%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522cltwzozhu00063b6hbhvovj5c%2522%252C%2522activeTabId%2522%253A%2522cltwzozhu00053b6hv0ae39js%2522%257D%252C%2522cltwzozhu00043b6h518r410l%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522cltwzozhu00043b6h518r410l%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Afalse%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D). We plan in the future to implement events you can listen to instead of needing to override the handler itself. Probably would be worth adding an example of this to the docs as other people have been confused by this as well.

Thanks for mentioning this @sashamilenkovic, I ran into a similar issue with `performTransfer` as specifying it caused the default transfer functionality to break, which was unexpected. Event handlers / listeners would be a much better solution or this needs to be more widely documented as myself and others are wasting a lot of time figuring this out

**Comment by sashamilenkovic** [comment]
As of `v0.2.0` There are now both global and parent scoped event listeners: https://drag-and-drop.formkit.com/#events
